# Generated by Django 3.1.7 on 2021-03-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image_of_letter', models.ImageField(blank=True, null=True, upload_to='researchdata/letters')),
                ('item_number', models.CharField(blank=True, max_length=255, null=True)),
                ('repository', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_reproduce_text', models.BooleanField(blank=True, null=True)),
                ('permission_reproduce_image', models.BooleanField(blank=True, null=True)),
                ('transcription_plain', models.TextField(blank=True, null=True)),
                ('transcription_normalized', models.TextField(blank=True, null=True)),
                ('sent_date', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_time', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_from_location', models.TextField(blank=True, null=True)),
                ('sent_to_location', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letter_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letter_lastupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
        ),
        migrations.CreateModel(
            name='LetterContentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='M2MLetterPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.letter')),
            ],
        ),
        migrations.CreateModel(
            name='M2MPersonPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SlGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlLetterCollection',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentAppearance',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentBodilyActivity',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentBodyPart',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentCommentary',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentCondition',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentContext',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentEmotion',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentEstimatedProportionOfLetter',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentImmaterial',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentRole',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentSensation',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentState',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentSubject',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlLetterContentTreatment',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlM2MLetterLetterRelationshipType',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlM2MLetterPersonRelationshipType',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlM2MPersonPersonRelationshipType',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlPersonGender',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlPersonRank',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlPersonReligion',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='SlPersonTitle',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('informal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('date_active', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=True)),
                ('letter', models.ManyToManyField(blank=True, related_name='related_person', through='researchdata.M2MLetterPerson', to='researchdata.Letter')),
                ('person', models.ManyToManyField(blank=True, related_name='_person_person_+', through='researchdata.M2MPersonPerson', to='researchdata.Person')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slpersongender')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slpersonrank')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slpersonreligion')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slpersontitle')),
            ],
        ),
        migrations.AddField(
            model_name='m2mpersonperson',
            name='person_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_1', to='researchdata.person'),
        ),
        migrations.AddField(
            model_name='m2mpersonperson',
            name='person_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_2', to='researchdata.person'),
        ),
        migrations.AddField(
            model_name='m2mletterperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.person'),
        ),
        migrations.CreateModel(
            name='M2MLetterLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_1', to='researchdata.letter')),
                ('letter_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_2', to='researchdata.letter')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.slm2mletterletterrelationshiptype')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='letter',
            field=models.ManyToManyField(blank=True, related_name='_letter_letter_+', through='researchdata.M2MLetterLetter', to='researchdata.Letter'),
        ),
        migrations.AddField(
            model_name='letter',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='related_letter', through='researchdata.M2MLetterPerson', to='researchdata.Person'),
        ),
        migrations.AddField(
            model_name='m2mpersonperson',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.slm2mpersonpersonrelationshiptype'),
        ),
        migrations.AddField(
            model_name='m2mletterperson',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchdata.slm2mletterpersonrelationshiptype'),
        ),
        migrations.CreateModel(
            name='LetterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('admin_published', models.BooleanField(default=True)),
                ('content_type', models.ManyToManyField(blank=True, db_table='researchdata_m2m_lettercontent_lettercontenttype', related_name='lettercontent', to='researchdata.LetterContentType')),
                ('letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchdata.letter')),
                ('location', models.ManyToManyField(blank=True, db_table='researchdata_m2m_lettercontent_lettercontentlocation', related_name='lettercontent', to='researchdata.LetterContentLocation')),
                ('appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentappearance')),
                ('bodily_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentbodilyactivity')),
                ('body_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentbodypart')),
                ('commentary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentcommentary')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentcondition')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentcontext')),
                ('emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentemotion')),
                ('estimated_proportion_of_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentestimatedproportionofletter')),
                ('immaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentimmaterial')),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentrole')),
                ('sensation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentsensation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentstate')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentsubject')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontenttreatment')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercollection'),
        ),
    ]
