# Generated by Django 3.1.7 on 2021-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='informal_name',
        ),
        migrations.AddField(
            model_name='m2mletterperson',
            name='person_form_of_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
