# Generated by Django 3.1.7 on 2021-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='person',
            name='year_active_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_active_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SlLetterPersonSubject',
        ),
    ]
