# Generated by Django 3.1.7 on 2021-03-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lettercontent',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='lettercontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lettercontent',
            name='estimated_proportion_of_letter',
        ),
        migrations.RemoveField(
            model_name='lettercontent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lettercontent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='letter',
        ),
        migrations.AddField(
            model_name='letter',
            name='commentary',
            field=models.ManyToManyField(blank=True, related_name='letter', to='researchdata.SlLetterContentCommentary'),
        ),
        migrations.AddField(
            model_name='letter',
            name='content_type',
            field=models.ManyToManyField(blank=True, related_name='letter', to='researchdata.SlLetterContentType'),
        ),
        migrations.AddField(
            model_name='letter',
            name='estimated_proportion_of_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.sllettercontentestimatedproportionofletter'),
        ),
        migrations.AddField(
            model_name='letter',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='letter', to='researchdata.SlLetterContentLocation'),
        ),
        migrations.AddField(
            model_name='letter',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='letter', to='researchdata.SlLetterContentState'),
        ),
        migrations.DeleteModel(
            name='M2MLetterPerson',
        ),
    ]
