# Generated by Django 3.2.4 on 2021-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_auto_20210625_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'middle_name', 'id']},
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_to_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_to_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
