# Generated by Django 3.2.5 on 2021-09-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_auto_20210625_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlLetterPersonGender',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.AddField(
            model_name='letterperson',
            name='person_other_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slletterpersongender', verbose_name='Gender of person/people (if not specified in Person table)'),
        ),
    ]
