# Generated by Django 3.1.7 on 2021-03-12 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_auto_20210312_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_date_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='sent_date_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
