# Generated by Django 3.1.7 on 2021-03-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0003_auto_20210308_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettercontent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchdata.person', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lettercontent',
            unique_together={('letter', 'person_other', 'person_letter_relationship')},
        ),
    ]
