# Generated by Django 3.1.7 on 2021-03-12 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0004_auto_20210312_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='sent_date_as_given',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sent_date_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sent_date_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='letterperson',
            name='person_other',
            field=models.TextField(blank=True, null=True, verbose_name='Person/People (if not specified in Person table)'),
        ),
    ]
