# Generated by Django 3.1.7 on 2021-03-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0005_auto_20210308_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettercontent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchdata.person'),
        ),
        migrations.AlterUniqueTogether(
            name='lettercontent',
            unique_together={('letter', 'person'), ('letter', 'person_other')},
        ),
    ]
