# Generated by Django 3.2.5 on 2021-10-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='sent_date_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
