# Generated by Django 3.2.9 on 2021-11-03 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0006_letter_sent_date_is_approximate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='sent_date_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(99), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
