# Generated by Django 3.2.15 on 2022-10-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0007_alter_letter_sent_date_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='researchdata/letters-thumbnails'),
        ),
    ]
