# Generated by Django 3.2.15 on 2022-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0009_letterimage_datamigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='permission_reproduce_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='permission_reproduce_text',
            field=models.BooleanField(default=True),
        ),
    ]
