# Generated by Django 3.2.15 on 2022-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0010_auto_20221018_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='admin_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='permission_reproduce_image',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='permission_reproduce_text',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
