# Generated by Django 3.2.16 on 2022-11-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0013_auto_20221102_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_letter', to='researchdata.sllettercollection'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='commentary',
            field=models.ManyToManyField(blank=True, related_name='related_letter', to='researchdata.SlLetterCommentary'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='estimated_proportion_of_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_letter', to='researchdata.slletterestimatedproportionofletter'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.ManyToManyField(blank=True, related_name='related_letter', to='researchdata.SlLetterType'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='related_letter', to='researchdata.SlLetterLocation'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_letter', to='researchdata.slletterrepository'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_person', to='researchdata.slpersongender'),
        ),
    ]
