# Generated by Django 3.2.16 on 2022-11-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0014_auto_20221108_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlCountry',
            fields=[
                ('slgeneric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='researchdata.slgeneric')),
            ],
            bases=('researchdata.slgeneric',),
        ),
        migrations.CreateModel(
            name='LetterPublicTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=150)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
                ('approved_by_project_team', models.BooleanField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterpublictranscription', to='researchdata.letter')),
                ('person_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researchdata.slcountry')),
            ],
        ),
        migrations.CreateModel(
            name='LetterImagePublicTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('letter_image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='letterimagepublictranscription', to='researchdata.letterimage')),
                ('letter_public_transcription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='letterimagepublictranscription', to='researchdata.letterpublictranscription')),
            ],
        ),
    ]
