# Generated by Django 3.2.16 on 2022-12-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0016_countrydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='copyright_holder_untraced',
            field=models.BooleanField(default=False),
        ),
    ]
