# Generated by Django 4.2.1 on 2023-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0018_auto_20221205_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter',
            field=models.ManyToManyField(blank=True, through='researchdata.M2MLetterLetter', to='researchdata.letter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.ManyToManyField(blank=True, through='researchdata.M2MPersonPerson', to='researchdata.person'),
        ),
    ]
